[options]
admin_passwd = admin

db_host = ${PGHOST}
db_port = ${PGPORT}
db_user = ${PGUSER}
db_password = ${PGPASSWORD}

# 🔥 Core + your modules
addons_path = /opt/odoo/addons,/mnt/extra-addons

http_port = 8069
proxy_mode = True